[package]
name = "vooya"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Public Rust authoring API for Vooya."

[dependencies]
js-sys = "=0.3.92"
vooya-core = { path = "../../packages/core/rust" }
vooya-macros = { path = "../vooya-macros" }
wasm-bindgen = "=0.2.115"
