// Webpack hook types are intentionally not imported: this package keeps the
// integration boundary compatible with supported Webpack 5 releases.
// @ts-nocheck
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { buildApplication } from "@vooya/build-core";
import { generateVooDeclaration, parseVooComponent } from "@vooya/compiler";
export function vooyaWebpack({ framework = "vue", rust = {}, cacheDirectory } : { framework?: "vue" | "react"; rust?: object; cacheDirectory?: string } = {}) { return { apply(compiler: any) { let result: any, needsBuild = true, generation = 0; const compile = () => { const root = compiler.context, cacheRoot = cacheDirectory ? resolve(root, cacheDirectory) : resolve(root, ".voo-cache", "webpack"), components = files(root).map((id) => ({ ...parseVooComponent(readFileSync(id, "utf8"), id), id })).filter((item) => item.format === "source"); for (const item of components) writeFileSync(item.id.replace(/\.voo$/, ".d.voo.ts"), generateVooDeclaration(item, framework)); result = buildApplication({ applicationRoot: root, components, rust, cacheRoot, outputDir: resolve(cacheRoot, "artifacts", String(++generation)), buildMode: compiler.watchMode ? "development" : "production" }); needsBuild = false; }; compiler.hooks.watchRun.tap("vooya", (watching: any) => { const changed = watching.modifiedFiles ?? new Set(); if ([...changed].some((file: string) => file.endsWith(".voo") || result?.watchedFiles?.some((root: string) => file.startsWith(root)))) needsBuild = true; }); compiler.hooks.beforeCompile.tapPromise("vooya", async () => { if (needsBuild) compile(); }); compiler.hooks.thisCompilation.tap("vooya", (compilation: any) => { compilation.__vooyaBuild = result; for (const file of result?.watchedFiles ?? []) compilation.contextDependencies.add(file); }); compiler.options.devServer ??= {}; compiler.options.devServer.liveReload = true; } }; }
function files(directory: string): string[] { const ignored = new Set([".git", ".voo-cache", "dist", "node_modules", "target"]), result: string[] = []; for (const entry of readdirSync(directory, { withFileTypes: true })) { if (ignored.has(entry.name)) continue; const path = join(directory, entry.name); if (entry.isDirectory()) result.push(...files(path)); else if (entry.isFile() && entry.name.endsWith(".voo")) result.push(path); } return result; }
