import { VooyaUserError } from "./errors.js";
import type { RustComponentContract, RustEventsSchema, RustPropsSchema, RustSchemaParameter, RustStoreSchema, RustTypeSchema, RustSchemaSource } from "./schema.js";

/** A source-addressable failure in a Store's declared snapshot schema. */
export class RustSnapshotSchemaError extends VooyaUserError {
  constructor(readonly storeId: string, readonly fieldPath: string, readonly reason: string, readonly source?: RustSchemaSource) {
    const location = source ? `${source.file}${source.line ? `:${source.line}${source.column ? `:${source.column}` : ""}` : ""}: ` : "";
    super(`${location}Cannot generate Store snapshot ${fieldPath} for ${storeId}: ${reason} Use supported owned ABI-v1 values in snapshots.`, { kind: "snapshot-schema" });
  }
}

export type SchemaDeclarationFramework = "vue" | "react" | "solid" | "svelte" | "octane";

/** The four lifecycle error stages the runtime can emit; kept in one place so
 * every framework declaration exposes the same union. */
const ERROR_STAGE_UNION = '"load" | "mount" | "update" | "dispose"';

export interface RustSchemaDeclarationInput {
  contract: RustComponentContract;
  framework: SchemaDeclarationFramework;
  types?: RustTypeSchema[];
}

export function generateRustSchemaDeclaration({ contract, framework, types = [] }: RustSchemaDeclarationInput): string {
  const component = contract.component;
  const props = contract.props;
  const events = contract.events;
  const ownerGroup = props?.group ?? events?.group ?? component.group;
  const { code: typeCode, names } = generateTypes(types, referencedTypeNames(contract), component.id, ownerGroup);
  const propsCode = props ? generateProps(props, component.name, names.forGroup(props.group ?? component.group)) : `interface ${component.name}Props {}`;
  const eventsCode = events ? generateEvents(events, component.name, names.forGroup(events.group ?? component.group)) : `type ${component.name}Events = ["error"];`;
  if (framework === "vue") {
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ComponentOptionsMixin, DefineComponent } from "vue";\n\n${typeCode}${propsCode}\n${eventsCode}\ndeclare const component: DefineComponent<\n  ${component.name}Props,\n  {},\n  {},\n  {},\n  {},\n  ComponentOptionsMixin,\n  ComponentOptionsMixin,\n  ${component.name}Events\n>;\n\nexport default component;\n`;
  }
  if (framework === "react" || framework === "octane") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map((parameter) => namedParameterType(parameter, names.forGroup(events.group ?? component.group))).join(", ")}) => void;`).join("\n") : "";
    const hostProps = [eventProps, `  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;`].filter(Boolean).join("\n");
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ${framework === "octane" ? "ComponentBody as ComponentType" : "ComponentType"} } from "${framework}";\n\n${typeCode}${propsCode.replace(`interface ${component.name}Props`, `interface ${component.name}Props`)}\n\ndeclare const component: ComponentType<${component.name}Props & {\n${hostProps}\n}>;\n\nexport default component;\n`;
  }
  if (framework === "solid") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map((parameter) => namedParameterType(parameter, names.forGroup(events.group ?? component.group))).join(", ")}) => void;`).join("\n") : "";
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { Component } from "solid-js";\n\n${typeCode}${propsCode}\n\ndeclare const component: Component<${component.name}Props & {\n${eventProps}\n  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n  class?: string;\n  className?: string;\n}>;\n\nexport default component;\n`;
  }
  if (framework === "svelte") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map((parameter) => namedParameterType(parameter, names.forGroup(events.group ?? component.group))).join(", ")}) => void;`).join("\n") : "";
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { Component } from "svelte";\n\n${typeCode}${propsCode}\n\ndeclare const component: Component<${component.name}Props & {\n${eventProps}\n  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n  class?: string;\n  className?: string;\n}>;\n\nexport default component;\n`;
  }
  throw new Error(`Unknown schema declaration framework "${framework}".`);
}

interface TypeNames {
  get(reference: string): string | undefined;
  has(name: string): boolean;
  forGroup(group: string | null | undefined): TypeNames;
}

interface TypeReference {
  reference: string;
  group?: string | null;
}

function referenceKey(reference: string, group?: string | null): string {
  return JSON.stringify([group ?? null, reference]);
}

function generateTypes(types: RustTypeSchema[], required: TypeReference[], ownerId: string, ownerGroup?: string | null, snapshotStore?: RustStoreSchema): { code: string; names: TypeNames; opaqueSnapshot: boolean } {
  // Index and coalesce FromJs/ToJs records once, rather than scanning all
  // schemas and serializing their shapes for every reference.
  const byName = new Map<string, RustTypeSchema[]>();
  const identities = new Set<string>();
  for (const type of types) {
    const identity = JSON.stringify([type.name, type.group ?? null, type.shape]);
    if (identities.has(identity)) continue;
    identities.add(identity);
    const bucket = byName.get(type.name) ?? [];
    bucket.push(type);
    byName.set(type.name, bucket);
  }
  const pending = [...required];
  const resolved = new Map<string, RustTypeSchema | undefined>();
  const selected = new Set<RustTypeSchema>();
  while (pending.length) {
    const { reference, group } = pending.pop()!;
    const key = referenceKey(reference, group);
    if (resolved.has(key)) continue;
    const type = resolveNamedType(byName, reference, group, ownerId);
    resolved.set(key, type);
    if (!type || selected.has(type)) continue;
    selected.add(type);
    if (type.shape.kind === "struct") {
      for (const field of type.shape.fields) {
        for (const nested of referencedTypeNamesFromType(field.type)) {
          pending.push({ reference: nested, group: type.group });
        }
      }
    }
  }
  const aliases = allocateTypeNames([...selected]);
  const emittedNames = new Set(aliases.values());
  const forGroup = (group?: string | null): TypeNames => ({
    get(reference) {
      const type = resolved.get(referenceKey(reference, group));
      return type ? aliases.get(type) : undefined;
    },
    has: (name) => emittedNames.has(name),
    forGroup,
  });
  let opaqueSnapshot = false;
  if (snapshotStore) {
    const visit = (reference: string, group: string | null | undefined, path: string, source: RustSchemaSource | undefined, ancestors: Set<RustTypeSchema>, selfType?: RustTypeSchema) => {
      try { declarationType(reference, forGroup(group)); } catch (error) {
        if (!(error instanceof Error)) throw error;
        throw new RustSnapshotSchemaError(snapshotStore.id, path, error.message, source);
      }
      for (const nested of referencedTypeNamesFromType(reference)) {
        const type = nested === "Self" ? selfType : resolved.get(referenceKey(nested, group));
        // Missing metadata can describe a hand-written ToJs value. It is opaque,
        // not evidence that this value is a supported, precise owned schema.
        if (!type) { opaqueSnapshot = true; continue; }
        if (ancestors.has(type)) throw new RustSnapshotSchemaError(snapshotStore.id, path, `Recursive Rust schema reference "${nested}" is not supported.`, source);
        if (type.shape.kind === "struct") {
          const next = new Set(ancestors).add(type);
          for (const field of type.shape.fields) {
            visit(field.type, type.group, `${path}.${field.name}`, field.source ?? (type.group ? { file: type.group } : source), next, type);
          }
        }
      }
    };
    if (snapshotStore.snapshot) visit(snapshotStore.snapshot, snapshotStore.group, snapshotStore.snapshot, snapshotStore.snapshotSource ?? (snapshotStore.group ? { file: snapshotStore.group } : undefined), new Set());
    else opaqueSnapshot = true;
  }
  const code = [...selected]
    .sort((a, b) => compareText(aliases.get(a)!, aliases.get(b)!))
    .map((type) => generateNamedType(type, forGroup(type.group), aliases.get(type)!)).join("");
  return { code, names: forGroup(ownerGroup), opaqueSnapshot };
}

function compareText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Allocate before rendering so every member of a collision is renamed,
 * independently of schema or field traversal order. */
function allocateTypeNames(types: RustTypeSchema[]): Map<RustTypeSchema, string> {
  const counts = new Map<string, number>();
  for (const type of types) counts.set(type.name, (counts.get(type.name) ?? 0) + 1);
  const used = new Set(types.filter((type) => counts.get(type.name) === 1).map((type) => type.name));
  const aliases = new Map<RustTypeSchema, string>();
  for (const type of [...types].sort((a, b) => compareText(a.group ?? "", b.group ?? "") || compareText(a.id, b.id))) {
    if (counts.get(type.name) === 1) {
      aliases.set(type, type.name);
      continue;
    }
    const parts = sourceModule(type.group).split("/").filter(Boolean);
    let base = type.name;
    let alias = base;
    for (let depth = 1; depth <= parts.length; depth += 1) {
      const prefix = parts.slice(-depth).join("_").split(/[^A-Za-z0-9]+/)
        .filter(Boolean).map((part) => part[0].toUpperCase() + part.slice(1)).join("");
      base = `${prefix}${type.name}`;
      if (!/^[A-Za-z_]/.test(base)) base = `Type${base}`;
      alias = base;
      if (!used.has(alias)) break;
    }
    let suffix = 2;
    while (used.has(alias)) alias = `${base}${suffix++}`;
    used.add(alias);
    aliases.set(type, alias);
  }
  return aliases;
}

function resolveNamedType(byName: ReadonlyMap<string, RustTypeSchema[]>, reference: string, ownerGroup: string | null | undefined, ownerId: string): RustTypeSchema | undefined {
  const name = reference.split("::").at(-1) ?? reference;
  const candidates = byName.get(name) ?? [];
  const matches = reference.includes("::")
    ? candidates.filter((type) => typeMatchesRustReference(type, reference, ownerGroup))
    : (() => {
        const scoped = ownerGroup ? candidates.filter((type) => type.group === ownerGroup) : [];
        return scoped.length > 0 ? scoped : candidates;
      })();
  if (matches.length > 1) {
    throw new Error(
      `Ambiguous Rust type schema reference "${reference}" for ${ownerId}. ` +
      `Candidates are: ${matches.map(formatTypeCandidate).join(", ")}.`,
    );
  }
  return matches[0];
}

function formatTypeCandidate(type: RustTypeSchema): string {
  return `${type.id} (${type.group ?? "source group unavailable"})`;
}

/** Conventional source layout only; source groups cannot resolve Rust use
 * aliases, inline modules, or #[path] overrides. */
function sourceModule(group?: string | null): string {
  return (group ?? "").replaceAll("\\", "/").replace(/\.rs$/, "").replace(/(?:^|\/)(?:mod|lib|main)$/, "");
}

function typeMatchesRustReference(type: RustTypeSchema, reference: string, ownerGroup?: string | null): boolean {
  if (!type.group) return false;
  const parts = reference.split("::").slice(0, -1);
  const target = sourceModule(type.group);
  if (parts[0] === "self" || parts[0] === "super") {
    if (!ownerGroup) return false;
    const owner = sourceModule(ownerGroup).split("/");
    if (parts[0] === "self") parts.shift();
    while (parts[0] === "super") {
      parts.shift();
      owner.pop();
    }
    return target === [...owner, ...parts].join("/");
  }
  if (parts[0] === "crate") {
    parts.shift();
    const normalized = type.group.replaceAll("\\", "/");
    const root = normalized.lastIndexOf("/src/");
    const relative = normalized.startsWith("src/") ? target.slice(4)
      : root >= 0 ? target.slice(root + 5) : undefined;
    return relative === parts.join("/");
  }
  const modulePath = parts.join("/");
  return target === modulePath || target.endsWith(`/${modulePath}`);
}

function generateNamedType(type: RustTypeSchema, names: TypeNames, alias: string): string {
  if (type.shape.kind === "enum") {
    return `export type ${alias} = ${type.shape.variants.map((variant) => `{ type: ${JSON.stringify(variant)} }`).join(" | ")};\n\n`;
  }
  try {
    return `export interface ${alias} {\n${type.shape.fields.map((field) => `  ${propertyName(field.name)}${isOptional(field.type) ? "?" : ""}: ${declarationType(field.type, names)};`).join("\n")}\n}\n\n`;
  } catch (error) {
    if (!(error instanceof Error) || !/^Unsupported (?:Rust schema type|map key type)/.test(error.message)) throw error;
    // The derive schema establishes an object even when one field cannot be
    // represented by ABI-v1 TypeScript declarations.
    return `export type ${alias} = Record<string, unknown>;\n\n`;
  }
}

function referencedTypeNames(contract: RustComponentContract): TypeReference[] {
  const types: TypeReference[] = [];
  for (const field of contract.props?.fields ?? []) {
    for (const name of referencedTypeNamesFromType(field.type)) types.push({ reference: name, group: contract.props?.group ?? contract.component.group });
  }
  for (const method of contract.events?.methods ?? []) {
    for (const parameter of method.params) {
      for (const name of referencedTypeNamesFromType(parameter.type)) types.push({ reference: name, group: contract.events?.group ?? contract.component.group });
    }
  }
  return types;
}

function referencedTypeNamesFromType(type: string): string[] {
  const normalized = type.replace(/\s+/g, "");
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|i64|u64|i128|u128|f32|f64|bool|String)$/.test(normalized)) return [];
  const option = unwrapGeneric(normalized, "Option") ?? unwrapGeneric(normalized, "Vec");
  if (option) return referencedTypeNamesFromType(option);
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) return splitTopLevel(map).flatMap(referencedTypeNamesFromType);
  if (normalized.startsWith("(") && normalized.endsWith(")")) return splitTopLevel(normalized.slice(1, -1)).flatMap(referencedTypeNamesFromType);
  return isNamedTypeReference(normalized) ? [normalized] : [];
}

export function generateRustStoreDeclaration(
  store: RustStoreSchema,
  framework: SchemaDeclarationFramework = "vue",
  types: RustTypeSchema[] = [],
): string {
  const name = store.name.split("::").at(-1) ?? store.name;
  const required = new Set<string>();
  for (const type of [store.snapshot, ...store.actions.flatMap((action) => action.params.map((parameter) => parameter.type))]) {
    if (type) for (const referenced of referencedTypeNamesFromType(type)) required.add(referenced);
  }
  const { code: typeCode, names, opaqueSnapshot } = generateTypes(types, [...required].map((reference) => ({ reference, group: store.group })), store.id, store.group, store);
  // A hand-written ToJs implementation may emit any JavaScript value, so a
  // missing schema cannot justify an object-shaped fallback.
  const snapshot = store.snapshot ? declarationType(store.snapshot, names) : "unknown";
  if (names.has(`${name}Snapshot`) && snapshot !== `${name}Snapshot`) {
    throw new Error(`Rust type "${name}Snapshot" conflicts with the generated snapshot alias for ${store.id}.`);
  }
  const actions = store.actions
    .map((action) => `  ${action.name}(...args: [${action.params.map((parameter) => parameterType(parameter, names)).join(", ")}]): void;`)
    .join("\n");
  const hookActions = store.actions
    .map((action) => `  ${action.name}(...args: [${action.params.map((parameter) => parameterType(parameter, names)).join(", ")}]): void;`)
    .join("\n");
  const adapterImport = framework === "vue"
    ? `import type { Ref } from "vue";\nimport type { VooyaStoreOptions } from "@vooya/vue";\n\n`
    : framework === "solid"
      ? `import type { Accessor } from "solid-js";\nimport type { VooyaStoreOptions } from "@vooya/solid";\n\n`
      : framework === "svelte"
        ? `import type { Readable } from "svelte/store";\nimport type { VooyaStoreOptions } from "@vooya/svelte";\n\n`
        : `import type { VooyaStoreOptions } from "@vooya/${framework}";\n\n`;
  const stateType = framework === "vue"
    ? `Readonly<Ref<${name}Snapshot | undefined>>`
    : framework === "solid"
      ? `Accessor<${name}Snapshot | undefined>`
      : framework === "svelte"
        ? `Readable<${name}Snapshot | undefined>`
        : `${name}Snapshot | undefined`;
  const generatedHook = `\nexport declare function use${name}(options?: VooyaStoreOptions): {\n  state: ${name}Snapshot | undefined;\n${hookActions}\n};\n`;
  const typedGeneratedHook = generatedHook.replace(`state: ${name}Snapshot | undefined;`, `state: ${stateType};`);
  const snapshotNote = opaqueSnapshot ? "/** Snapshot schema metadata is missing for one or more values. Those values remain opaque (unknown); no precise ABI shape is asserted. */\n" : "";
  const snapshotAlias = snapshot === `${name}Snapshot` ? "" : `export type ${name}Snapshot = ${snapshot};\n\n`;
  return `// Generated by @vooya/build-core. Do not edit.\n${adapterImport}${typeCode}${snapshotNote}${snapshotAlias}export interface ${name}Store {\n  getSnapshot(): ${name}Snapshot;\n  subscribe(listener: () => void): () => void;\n${actions}\n  dispose(): void;\n}\n\nexport declare function create${name}Store(): Promise<${name}Store>;\nexport default create${name}Store;\n${typedGeneratedHook}`;
}

/** Preserve supported containers while falling back only at an unresolved leaf. */
function declarationType(type: string, names: TypeNames): string {
  const normalized = type.replace(/\s+/g, "");
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|i64|u64|i128|u128|f32|f64|bool|String)$/.test(normalized)) {
    return rustTypeToTypeScript(normalized);
  }
  const option = unwrapGeneric(normalized, "Option");
  if (option) return `${declarationType(option, names)} | null`;
  const vector = unwrapGeneric(normalized, "Vec");
  if (vector) return `Array<${declarationType(vector, names)}>`;
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) {
    const [key, value] = splitTopLevel(map);
    if (key !== "String") throw new Error(`Unsupported map key type "${key}".`);
    return `Record<string, ${declarationType(value, names)}>`;
  }
  if (normalized.startsWith("(") && normalized.endsWith(")")) {
    return `[${splitTopLevel(normalized.slice(1, -1)).map((item) => declarationType(item, names)).join(", ")}]`;
  }
  if (isNamedTypeReference(normalized)) {
    return names.get(normalized) ?? "unknown";
  }
  return rustTypeToTypeScript(normalized);
}

function generateProps(props: RustPropsSchema, componentName: string, names: TypeNames): string {
  return `interface ${componentName}Props {\n${props.fields.map((field) => `  ${propertyName(field.name)}${isOptional(field.type) ? "?" : ""}: ${parameterType(field, names)};`).join("\n")}\n}`;
}

function generateEvents(events: RustEventsSchema, componentName: string, names: TypeNames): string {
  if (events.methods.length === 0) return `type ${componentName}Events = ["error"];`;
  return `type ${componentName}Events = {\n${events.methods.map((event) => `  ${propertyName(event.name)}: (${event.params.map((parameter) => namedParameterType(parameter, names)).join(", ")}) => void;`).join("\n")}\n  error: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n}`;
}

function parameterType(parameter: RustSchemaParameter, names: TypeNames): string {
  return declarationType(parameter.type, names);
}

function namedParameterType(parameter: RustSchemaParameter, names: TypeNames): string {
  return `${propertyName(parameter.name)}: ${parameterType(parameter, names)}`;
}

export function rustTypeToTypeScript(type: string): string {
  const normalized = type.replace(/\s+/g, "");
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|f32|f64)$/.test(normalized)) return "number";
  if (/^(?:i64|u64|i128|u128)$/.test(normalized)) return "bigint";
  if (normalized === "bool") return "boolean";
  if (normalized === "String") return "string";
  const option = unwrapGeneric(normalized, "Option");
  if (option) return `${rustTypeToTypeScript(option)} | null`;
  const vector = unwrapGeneric(normalized, "Vec");
  if (vector) return `Array<${rustTypeToTypeScript(vector)}>`;
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) {
    const [key, value] = splitTopLevel(map);
    if (key !== "String") throw new Error(`Unsupported map key type "${key}".`);
    return `Record<string, ${rustTypeToTypeScript(value)}>`;
  }
  if (normalized.startsWith("(") && normalized.endsWith(")")) {
    const items = splitTopLevel(normalized.slice(1, -1));
    return `[${items.map(rustTypeToTypeScript).join(", ")}]`;
  }
  if (isNamedTypeReference(normalized)) return normalized.split("::").at(-1) ?? normalized;
  throw new Error(`Unsupported Rust schema type "${type}".`);
}

/** Runtime constructor category used by framework adapters for the same ABI. */
export function rustTypeToRuntimeType(type: string): "number" | "bigint" | "boolean" | "string" | "array" | "object" {
  const normalized = type.replace(/\s+/g, "");
  const option = unwrapGeneric(normalized, "Option");
  if (option) return rustTypeToRuntimeType(option);
  if (normalized === "bool") return "boolean";
  if (normalized === "String") return "string";
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|f32|f64)$/.test(normalized)) return "number";
  if (/^(?:i64|u64|i128|u128)$/.test(normalized)) return "bigint";
  if (unwrapGeneric(normalized, "Vec") || (normalized.startsWith("(") && normalized.endsWith(")"))) return "array";
  if (unwrapGeneric(normalized, "BTreeMap") || unwrapGeneric(normalized, "HashMap") || isNamedTypeReference(normalized)) return "object";
  throw new Error(`Unsupported Rust runtime type "${type}".`);
}

function unwrapGeneric(type: string, name: string): string | undefined {
  const prefix = `${name}<`;
  return type.startsWith(prefix) && type.endsWith(">") ? type.slice(prefix.length, -1) : undefined;
}

function isNamedTypeReference(type: string): boolean {
  return /^(?:[A-Za-z_][A-Za-z0-9_]*::)*[A-Z][A-Za-z0-9_]*$/.test(type);
}

function splitTopLevel(value: string): string[] {
  const result: string[] = [];
  let start = 0;
  let depth = 0;
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "<" || value[index] === "(") depth += 1;
    else if (value[index] === ">" || value[index] === ")") depth -= 1;
    else if (value[index] === "," && depth === 0) {
      result.push(value.slice(start, index));
      start = index + 1;
    }
  }
  if (start < value.length) result.push(value.slice(start));
  return result.filter(Boolean);
}

function isOptional(type: string): boolean {
  return type.replace(/\s+/g, "").startsWith("Option<");
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function reactEventName(name: string): string {
  const pascal = name.split(/[-_]/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join("");
  return `on${pascal}`;
}
