import { VOO_ABI_VERSION } from "./runtime.js";

export function generateRustComponents(components, sourcePaths = new Map()) {
  const modules = components
    .map((component) => generateRustComponent(component, sourcePaths.get(component.id)))
    .join("\n\n");
  return `// Generated by @vooya/vite-plugin. Do not edit.
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn voo_abi_version() -> u32 {
    ${VOO_ABI_VERSION}
}

${modules}
`;
}

export function generatedComponentBinding(component) {
  const stem = rustStem(component.name);
  return {
    exportName: `voo_${stem}_mount`,
    disposeName: `voo_${stem}_dispose`,
    updateNames: Object.fromEntries(
      component.props.map((prop) => [prop.name, `voo_${stem}_update_${prop.name}`]),
    ),
    propsName: `Voo${component.name}Props`,
    eventsName: `Voo${component.name}Events`,
    contextName: `Voo${component.name}Context`,
  };
}

export function generatedComponentPrelude(component) {
  const { contextName } = generatedComponentBinding(component);
  return `use super::${contextName} as Context;\n`;
}

export function generatedAdapterDefinition(component) {
  return {
    abiVersion: VOO_ABI_VERSION,
    name: component.name,
    ...(component.style?.scoped ? { scopeId: generatedScopeId(component) } : {}),
    props: component.props.map((prop) => ({
      name: prop.name,
      type: javascriptType(prop.rustType),
      required: prop.required,
      ...(prop.defaultValue === undefined
        ? {}
        : { defaultValue: parseDefaultValue(prop.defaultValue, prop.rustType) }),
    })),
    events: component.events.map((event) => ({
      name: event.name,
      parameters: event.parameters.map((parameter) => parameter.name),
    })),
  };
}

export function generatedScopeId(component) {
  const source = component.scopeSource ?? component.id ?? component.name;
  let hash = 0x811c9dc5;
  for (let index = 0; index < source.length; index += 1) {
    hash ^= source.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return `voo-${(hash >>> 0).toString(16)}`;
}

function generateRustComponent(component, sourcePath) {
  const stem = rustStem(component.name);
  const moduleName = `voo_${stem}_component`;
  const handlesName = `VOO_${stem.toUpperCase()}_HANDLES`;
  const { exportName, disposeName, updateNames, propsName, eventsName, contextName } =
    generatedComponentBinding(component);
  const mountParameters = component.props
    .map((prop) => `, ${prop.name}: ${prop.rustType}`)
    .join("");
  const updateFunctions = component.props
    .map(
      (prop) => `
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn ${updateNames[prop.name]}(handle: u32, value: ${prop.rustType}) {
    ${handlesName}.with(|handles| {
        if let Some(Some(component)) = handles.borrow().get(handle as usize) {
            component.update_${prop.name}(value);
        }
    });
}`,
    )
    .join("\n");

  const module = sourcePath
    ? `#[path = ${JSON.stringify(sourcePath)}]\nmod ${moduleName};`
    : `mod ${moduleName} {\n${indent(component.rust.content, 4)}\n}`;
  const propFields = component.props
    .map((prop) => `    pub ${prop.name}: ${prop.rustType},`)
    .join("\n");
  const propValues = component.props.map((prop) => `        ${prop.name},`).join("\n");
  const eventMethods = component.events.map(generateEventMethod).join("\n\n");
  const eventsDefinition = eventMethods
    ? `#[derive(Clone)]
pub struct ${eventsName} {
    target: web_sys::Element,
}

impl ${eventsName} {
    fn new(target: web_sys::Element) -> Self {
        Self { target }
    }

${eventMethods}
}`
    : `#[derive(Clone)]
pub struct ${eventsName};

impl ${eventsName} {
    fn new(_target: web_sys::Element) -> Self {
        Self
    }
}`;

  return `pub struct ${propsName} {
${propFields}
}

${eventsDefinition}

pub struct ${contextName} {
    pub host: web_sys::Element,
    pub props: ${propsName},
    pub events: ${eventsName},
}

${module}

thread_local! {
    static ${handlesName}: std::cell::RefCell<Vec<Option<${moduleName}::Component>>> = const { std::cell::RefCell::new(Vec::new()) };
}

#[wasm_bindgen::prelude::wasm_bindgen]
pub fn ${exportName}(
    host: web_sys::Element${mountParameters}
) -> Result<u32, wasm_bindgen::JsValue> {
    let context = ${contextName} {
        host: host.clone(),
        props: ${propsName} {
${propValues}
        },
        events: ${eventsName}::new(host),
    };
    let component = ${moduleName}::mount(context)?;
    ${handlesName}.with(|handles| {
        let mut handles = handles.borrow_mut();
        handles.push(Some(component));
        Ok((handles.len() - 1) as u32)
    })
}

#[wasm_bindgen::prelude::wasm_bindgen]
pub fn ${disposeName}(handle: u32) {
    let component = ${handlesName}.with(|handles| {
        handles
            .borrow_mut()
            .get_mut(handle as usize)
            .and_then(Option::take)
    });
    if let Some(mut component) = component {
        component.dispose();
    }
}${updateFunctions}`;
}

function generateEventMethod(event) {
  const methodName = rustStem(event.name);
  const parameters = event.parameters
    .map((parameter) => `${parameter.name}: ${parameter.rustType}`)
    .join(", ");
  const detail = generateEventDetail(event.parameters);
  return `    pub fn ${methodName}(&self${parameters ? `, ${parameters}` : ""}) -> Result<(), wasm_bindgen::JsValue> {
${indent(detail, 8)}
        let init = web_sys::CustomEventInit::new();
        init.set_bubbles(true);
        init.set_detail(&detail);
        let event = web_sys::CustomEvent::new_with_event_init_dict("vooya-${event.name}", &init)?;
        self.target.dispatch_event(&event)?;
        Ok(())
    }`;
}

function generateEventDetail(parameters) {
  if (parameters.length === 0) return "let detail = wasm_bindgen::JsValue::UNDEFINED;";
  if (parameters.length === 1) {
    return `let detail = ${rustValueToJs(parameters[0].name, parameters[0].rustType)};`;
  }
  const pushes = parameters
    .map(
      (parameter) =>
        `detail.push(&${rustValueToJs(parameter.name, parameter.rustType)});`,
    )
    .join("\n");
  return `let detail = js_sys::Array::new();\n${pushes}\nlet detail: wasm_bindgen::JsValue = detail.into();`;
}

function rustValueToJs(name, rustType) {
  const type = javascriptType(rustType);
  if (type === "number") return `wasm_bindgen::JsValue::from_f64(${name} as f64)`;
  if (type === "boolean") return `wasm_bindgen::JsValue::from_bool(${name})`;
  return `wasm_bindgen::JsValue::from_str(&${name})`;
}

function rustStem(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .toLowerCase();
}

function javascriptType(rustType) {
  if (/^(?:[iu](?:8|16|32|64|128|size)|f(?:32|64))$/.test(rustType)) return "number";
  if (rustType === "bool") return "boolean";
  if (rustType === "String" || rustType === "str" || rustType === "&str") return "string";
  throw new Error(`Unsupported Voo prop type "${rustType}".`);
}

function parseDefaultValue(source, rustType) {
  const type = javascriptType(rustType);
  if (type === "number" && /^-?(?:\d+\.?\d*|\.\d+)$/.test(source)) return Number(source);
  if (type === "boolean" && /^(?:true|false)$/.test(source)) return source === "true";
  if (type === "string" && /^"(?:[^"\\]|\\.)*"$/.test(source)) return JSON.parse(source);
  throw new Error(`Invalid default value "${source}" for Rust type "${rustType}".`);
}

function indent(source, spaces) {
  const prefix = " ".repeat(spaces);
  return source
    .split(/\r?\n/)
    .map((line) => `${prefix}${line}`)
    .join("\n");
}
