import type { RustComponentContract, RustEventsSchema, RustPropsSchema, RustSchemaParameter, RustStoreSchema } from "./schema.js";

export type SchemaDeclarationFramework = "vue" | "react";

export interface RustSchemaDeclarationInput {
  contract: RustComponentContract;
  framework: SchemaDeclarationFramework;
}

export function generateRustSchemaDeclaration({ contract, framework }: RustSchemaDeclarationInput): string {
  const component = contract.component;
  const props = contract.props;
  const events = contract.events;
  const propsCode = props ? generateProps(props, component.name) : `interface ${component.name}Props {}`;
  const eventsCode = events ? generateEvents(events, component.name) : `type ${component.name}Events = ["error"];`;
  if (framework === "vue") {
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ComponentOptionsMixin, DefineComponent } from "vue";\n\n${propsCode}\n${eventsCode}\ndeclare const component: DefineComponent<\n  ${component.name}Props,\n  {},\n  {},\n  {},\n  {},\n  ComponentOptionsMixin,\n  ComponentOptionsMixin,\n  ${component.name}Events\n>;\n\nexport default component;\n`;
  }
  if (framework === "react") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map(parameterType).join(", ")}) => void;`).join("\n") : "";
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ComponentType } from "react";\n\n${propsCode.replace(`interface ${component.name}Props`, `interface ${component.name}Props`)}\n\ndeclare const component: ComponentType<${component.name}Props & {\n${eventProps}\n}>;\n\nexport default component;\n`;
  }
  throw new Error(`Unknown schema declaration framework "${framework}".`);
}

export function generateRustStoreDeclaration(store: RustStoreSchema): string {
  const snapshot = store.snapshot ? rustTypeToTypeScript(store.snapshot) : "unknown";
  const actions = store.actions.map((action) => `  ${action.name}(...args: [${action.params.map(parameterType).join(", ")}]): void;`).join("\n");
  return `// Generated by @vooya/build-core. Do not edit.\nexport type ${store.name}Snapshot = ${snapshot};\n\nexport interface ${store.name} {\n  getSnapshot(): ${store.name}Snapshot;\n  subscribe(listener: () => void): () => void;\n${actions}\n  dispose(): void;\n}\n`;
}

function generateProps(props: RustPropsSchema, componentName: string): string {
  return `interface ${componentName}Props {\n${props.fields.map((field) => `  ${propertyName(field.name)}${isOptional(field.type) ? "?" : ""}: ${parameterType(field)};`).join("\n")}\n}`;
}

function generateEvents(events: RustEventsSchema, componentName: string): string {
  if (events.methods.length === 0) return `type ${componentName}Events = ["error"];`;
  return `interface ${componentName}Events {\n${events.methods.map((event) => `  ${propertyName(event.name)}: (${event.params.map(parameterType).join(", ")}) => void;`).join("\n")}\n  error: (error: { stage: \"load\" | \"mount\"; cause: unknown }) => void;\n}`;
}

function parameterType(parameter: RustSchemaParameter): string {
  return rustTypeToTypeScript(parameter.type);
}

export function rustTypeToTypeScript(type: string): string {
  const normalized = type.replace(/\s+/g, "");
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|f32|f64)$/.test(normalized)) return "number";
  if (/^(?:i64|u64|i128|u128)$/.test(normalized)) return "bigint";
  if (normalized === "bool") return "boolean";
  if (normalized === "String") return "string";
  const option = unwrapGeneric(normalized, "Option");
  if (option) return `${rustTypeToTypeScript(option)} | null`;
  const vector = unwrapGeneric(normalized, "Vec");
  if (vector) return `Array<${rustTypeToTypeScript(vector)}>`;
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) {
    const [key, value] = splitTopLevel(map);
    if (key !== "String") throw new Error(`Unsupported map key type "${key}".`);
    return `Record<string, ${rustTypeToTypeScript(value)}>`;
  }
  if (normalized.startsWith("(") && normalized.endsWith(")")) {
    const items = splitTopLevel(normalized.slice(1, -1));
    return `[${items.map(rustTypeToTypeScript).join(", ")}]`;
  }
  if (/^[A-Z][A-Za-z0-9_:]*$/.test(normalized)) return normalized.split("::").at(-1) ?? normalized;
  throw new Error(`Unsupported Rust schema type "${type}".`);
}

function unwrapGeneric(type: string, name: string): string | undefined {
  const prefix = `${name}<`;
  return type.startsWith(prefix) && type.endsWith(">") ? type.slice(prefix.length, -1) : undefined;
}

function splitTopLevel(value: string): string[] {
  const result: string[] = [];
  let start = 0;
  let depth = 0;
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "<" || value[index] === "(") depth += 1;
    else if (value[index] === ">" || value[index] === ")") depth -= 1;
    else if (value[index] === "," && depth === 0) {
      result.push(value.slice(start, index));
      start = index + 1;
    }
  }
  if (start < value.length) result.push(value.slice(start));
  return result.filter(Boolean);
}

function isOptional(type: string): boolean {
  return type.replace(/\s+/g, "").startsWith("Option<");
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function reactEventName(name: string): string {
  const pascal = name.split(/[-_]/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join("");
  return `on${pascal}`;
}
