import type { RustComponentContract, RustEventsSchema, RustPropsSchema, RustSchemaParameter, RustStoreSchema } from "./schema.js";

export type SchemaDeclarationFramework = "vue" | "react" | "solid" | "svelte";

/** The four lifecycle error stages the runtime can emit; kept in one place so
 * every framework declaration exposes the same union. */
const ERROR_STAGE_UNION = '"load" | "mount" | "update" | "dispose"';

export interface RustSchemaDeclarationInput {
  contract: RustComponentContract;
  framework: SchemaDeclarationFramework;
}

export function generateRustSchemaDeclaration({ contract, framework }: RustSchemaDeclarationInput): string {
  const component = contract.component;
  const props = contract.props;
  const events = contract.events;
  const propsCode = props ? generateProps(props, component.name) : `interface ${component.name}Props {}`;
  const eventsCode = events ? generateEvents(events, component.name) : `type ${component.name}Events = ["error"];`;
  if (framework === "vue") {
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ComponentOptionsMixin, DefineComponent } from "vue";\n\n${propsCode}\n${eventsCode}\ndeclare const component: DefineComponent<\n  ${component.name}Props,\n  {},\n  {},\n  {},\n  {},\n  ComponentOptionsMixin,\n  ComponentOptionsMixin,\n  ${component.name}Events\n>;\n\nexport default component;\n`;
  }
  if (framework === "react") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map(namedParameterType).join(", ")}) => void;`).join("\n") : "";
    const hostProps = [eventProps, `  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;`].filter(Boolean).join("\n");
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { ComponentType } from "react";\n\n${propsCode.replace(`interface ${component.name}Props`, `interface ${component.name}Props`)}\n\ndeclare const component: ComponentType<${component.name}Props & {\n${hostProps}\n}>;\n\nexport default component;\n`;
  }
  if (framework === "solid") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map(namedParameterType).join(", ")}) => void;`).join("\n") : "";
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { Component } from "solid-js";\n\n${propsCode}\n\ndeclare const component: Component<${component.name}Props & {\n${eventProps}\n  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n  class?: string;\n  className?: string;\n}>;\n\nexport default component;\n`;
  }
  if (framework === "svelte") {
    const eventProps = events ? events.methods.map((event) => `  ${reactEventName(event.name)}?: (${event.params.map(namedParameterType).join(", ")}) => void;`).join("\n") : "";
    return `// Generated by @vooya/build-core. Do not edit.\nimport type { Component } from "svelte";\n\n${propsCode}\n\ndeclare const component: Component<${component.name}Props & {\n${eventProps}\n  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n  class?: string;\n  className?: string;\n}>;\n\nexport default component;\n`;
  }
  throw new Error(`Unknown schema declaration framework "${framework}".`);
}

export function generateRustStoreDeclaration(
  store: RustStoreSchema,
  framework: SchemaDeclarationFramework = "vue",
): string {
  const name = store.name.split("::").at(-1) ?? store.name;
  const snapshot = store.snapshot ? rustStoreSnapshotType(store.snapshot) : "unknown";
  const actions = store.actions
    .map((action) => `  ${action.name}(...args: [${action.params.map(parameterType).join(", ")}]): void;`)
    .join("\n");
  const hookActions = store.actions
    .map((action) => `  ${action.name}(...args: [${action.params.map(parameterType).join(", ")}]): void;`)
    .join("\n");
  const adapterImport = framework === "vue"
    ? `import type { Ref } from "vue";\nimport type { VooyaStoreOptions } from "@vooya/vue";\n\n`
    : framework === "solid"
      ? `import type { Accessor } from "solid-js";\nimport type { VooyaStoreOptions } from "@vooya/solid";\n\n`
      : framework === "svelte"
        ? `import type { Readable } from "svelte/store";\nimport type { VooyaStoreOptions } from "@vooya/svelte";\n\n`
        : `import type { VooyaStoreOptions } from "@vooya/react";\n\n`;
  const stateType = framework === "vue"
    ? `Readonly<Ref<${name}Snapshot | undefined>>`
    : framework === "solid"
      ? `Accessor<${name}Snapshot | undefined>`
      : framework === "svelte"
        ? `Readable<${name}Snapshot | undefined>`
        : `${name}Snapshot | undefined`;
  const generatedHook = `\nexport declare function use${name}(options?: VooyaStoreOptions): {\n  state: ${name}Snapshot | undefined;\n${hookActions}\n};\n`;
  const typedGeneratedHook = generatedHook.replace(`state: ${name}Snapshot | undefined;`, `state: ${stateType};`);
  return `// Generated by @vooya/build-core. Do not edit.\n${adapterImport}export type ${name}Snapshot = ${snapshot};\n\nexport interface ${name}Store {\n  getSnapshot(): ${name}Snapshot;\n  subscribe(listener: () => void): () => void;\n${actions}\n  dispose(): void;\n}\n\nexport declare function create${name}Store(): Promise<${name}Store>;\nexport default create${name}Store;\n${typedGeneratedHook}`;
}

/**
 * Store snapshots may refer to a user-defined `ToJs` struct. Until those
 * structs have their own schema records, keep the declaration valid and model
 * the wire value as an object rather than emitting an unresolved self-alias.
 */
function rustStoreSnapshotType(type: string): string {
  const normalized = type.replace(/\s+/g, "");
  if (/^[A-Z][A-Za-z0-9_:]*$/.test(normalized)) return "Record<string, unknown>";
  const option = unwrapGeneric(normalized, "Option");
  if (option) return `${rustStoreSnapshotType(option)} | null`;
  const vector = unwrapGeneric(normalized, "Vec");
  if (vector) return `Array<${rustStoreSnapshotType(vector)}>`;
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) {
    const [key, value] = splitTopLevel(map);
    return key === "String" ? `Record<string, ${rustStoreSnapshotType(value)}>` : rustTypeToTypeScript(normalized);
  }
  if (normalized.startsWith("(") && normalized.endsWith(")")) {
    return `[${splitTopLevel(normalized.slice(1, -1)).map(rustStoreSnapshotType).join(", ")}]`;
  }
  return rustTypeToTypeScript(normalized);
}

function generateProps(props: RustPropsSchema, componentName: string): string {
  return `interface ${componentName}Props {\n${props.fields.map((field) => `  ${propertyName(field.name)}${isOptional(field.type) ? "?" : ""}: ${parameterType(field)};`).join("\n")}\n}`;
}

function generateEvents(events: RustEventsSchema, componentName: string): string {
  if (events.methods.length === 0) return `type ${componentName}Events = ["error"];`;
  return `interface ${componentName}Events {\n${events.methods.map((event) => `  ${propertyName(event.name)}: (${event.params.map(namedParameterType).join(", ")}) => void;`).join("\n")}\n  error: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;\n}`;
}

function parameterType(parameter: RustSchemaParameter): string {
  return rustTypeToTypeScript(parameter.type);
}

function namedParameterType(parameter: RustSchemaParameter): string {
  return `${propertyName(parameter.name)}: ${parameterType(parameter)}`;
}

export function rustTypeToTypeScript(type: string): string {
  const normalized = type.replace(/\s+/g, "");
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|f32|f64)$/.test(normalized)) return "number";
  if (/^(?:i64|u64|i128|u128)$/.test(normalized)) return "bigint";
  if (normalized === "bool") return "boolean";
  if (normalized === "String") return "string";
  const option = unwrapGeneric(normalized, "Option");
  if (option) return `${rustTypeToTypeScript(option)} | null`;
  const vector = unwrapGeneric(normalized, "Vec");
  if (vector) return `Array<${rustTypeToTypeScript(vector)}>`;
  const map = unwrapGeneric(normalized, "BTreeMap") ?? unwrapGeneric(normalized, "HashMap");
  if (map) {
    const [key, value] = splitTopLevel(map);
    if (key !== "String") throw new Error(`Unsupported map key type "${key}".`);
    return `Record<string, ${rustTypeToTypeScript(value)}>`;
  }
  if (normalized.startsWith("(") && normalized.endsWith(")")) {
    const items = splitTopLevel(normalized.slice(1, -1));
    return `[${items.map(rustTypeToTypeScript).join(", ")}]`;
  }
  if (/^[A-Z][A-Za-z0-9_:]*$/.test(normalized)) return normalized.split("::").at(-1) ?? normalized;
  throw new Error(`Unsupported Rust schema type "${type}".`);
}

/** Runtime constructor category used by framework adapters for the same ABI. */
export function rustTypeToRuntimeType(type: string): "number" | "bigint" | "boolean" | "string" | "array" | "object" {
  const normalized = type.replace(/\s+/g, "");
  const option = unwrapGeneric(normalized, "Option");
  if (option) return rustTypeToRuntimeType(option);
  if (normalized === "bool") return "boolean";
  if (normalized === "String") return "string";
  if (/^(?:i8|u8|i16|u16|i32|u32|isize|usize|f32|f64)$/.test(normalized)) return "number";
  if (/^(?:i64|u64|i128|u128)$/.test(normalized)) return "bigint";
  if (unwrapGeneric(normalized, "Vec") || (normalized.startsWith("(") && normalized.endsWith(")"))) return "array";
  if (unwrapGeneric(normalized, "BTreeMap") || unwrapGeneric(normalized, "HashMap") || /^[A-Z][A-Za-z0-9_:]*$/.test(normalized)) return "object";
  throw new Error(`Unsupported Rust runtime type "${type}".`);
}

function unwrapGeneric(type: string, name: string): string | undefined {
  const prefix = `${name}<`;
  return type.startsWith(prefix) && type.endsWith(">") ? type.slice(prefix.length, -1) : undefined;
}

function splitTopLevel(value: string): string[] {
  const result: string[] = [];
  let start = 0;
  let depth = 0;
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "<" || value[index] === "(") depth += 1;
    else if (value[index] === ">" || value[index] === ")") depth -= 1;
    else if (value[index] === "," && depth === 0) {
      result.push(value.slice(start, index));
      start = index + 1;
    }
  }
  if (start < value.length) result.push(value.slice(start));
  return result.filter(Boolean);
}

function isOptional(type: string): boolean {
  return type.replace(/\s+/g, "").startsWith("Option<");
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function reactEventName(name: string): string {
  const pascal = name.split(/[-_]/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join("");
  return `on${pascal}`;
}
