import type { CodegenComponent } from "./types.js";
import { validatePublicAbi } from "./abi.js";

export type VooDeclarationFramework = "vue" | "react" | "solid" | "svelte";

/** The four lifecycle error stages the runtime can emit; kept in one place so
 * every framework declaration exposes the same union. */
const ERROR_STAGE_UNION = '"load" | "mount" | "update" | "dispose"';

export function generateVooDeclaration(component: CodegenComponent, framework: VooDeclarationFramework) {
  validatePublicAbi(component);
  if (framework === "react") return generateReactDeclaration(component);
  if (framework === "solid") return generateSolidDeclaration(component);
  if (framework === "svelte") return generateSvelteDeclaration(component);
  if (framework !== "vue") throw new Error(`Unknown Vooya framework "${framework}".`);
  return generateVueDeclaration(component);
}

function generateSvelteDeclaration(component: CodegenComponent) {
  const props = component.props
    .map(
      (prop) =>
        `  ${propertyName(prop.name)}${prop.required ? "" : "?"}: ${typescriptType(prop.rustType)};`,
    )
    .join("\n");
  const events = component.events
    .map((event) => {
      const parameters = event.parameters
        .map((parameter) => `${parameter.name}: ${typescriptType(parameter.rustType)}`)
        .join(", ");
      return `  ${reactEventName(event.name)}?: (${parameters}) => void;`;
    })
    .join("\n");

  return `// Generated by @vooya/vite. Do not edit.
import type { Component } from "svelte";

interface ${component.name}Props {
${props}
${events}
  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;
  class?: string;
  className?: string;
}

declare const component: Component<${component.name}Props>;

export default component;
`;
}


function generateVueDeclaration(component: CodegenComponent) {
  const props = component.props
    .map(
      (prop) =>
        `  ${propertyName(prop.name)}${prop.required ? "" : "?"}: ${typescriptType(prop.rustType)};`,
    )
    .join("\n");
  const events = component.events
    .map((event) => {
      const parameters = event.parameters
        .map((parameter) => `${parameter.name}: ${typescriptType(parameter.rustType)}`)
        .join(", ");
      return `  ${propertyName(event.name)}: (${parameters}) => void;`;
    })
    .join("\n");
  const eventsDefinition = component.events.length
    ? `interface ${component.name}Events {
${events}
  error: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;
}`
    : `type ${component.name}Events = ["error"];`;
  const emitsType = component.events.length
    ? `// @ts-expect-error Vue 3.5's EmitsOptions constraint requires an index signature,
// but preserving these literal event names keeps $emit type-safe for consumers.
  ${component.name}Events`
    : `  ${component.name}Events`;

  return `// Generated by @vooya/vite. Do not edit.
import type { ComponentOptionsMixin, DefineComponent } from "vue";

interface ${component.name}Props {
${props}
}

${eventsDefinition}

declare const component: DefineComponent<
  ${component.name}Props,
  {},
  {},
  {},
  {},
  ComponentOptionsMixin,
  ComponentOptionsMixin,
${emitsType}
>;

export default component;
`;
}

function generateReactDeclaration(component: CodegenComponent) {
  const props = component.props
    .map(
      (prop) =>
        `  ${propertyName(prop.name)}${prop.required ? "" : "?"}: ${typescriptType(prop.rustType)};`,
    )
    .join("\n");
  const events = component.events
    .map((event) => {
      const parameters = event.parameters
        .map((parameter) => `${parameter.name}: ${typescriptType(parameter.rustType)}`)
        .join(", ");
      return `  ${reactEventName(event.name)}?: (${parameters}) => void;`;
    })
    .join("\n");

  return `// Generated by @vooya/vite. Do not edit.
import type { ComponentType } from "react";

interface ${component.name}Props {
${props}
${events}
  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;
  className?: string;
}

declare const component: ComponentType<${component.name}Props>;

export default component;
`;
}

function generateSolidDeclaration(component: CodegenComponent) {
  const props = component.props
    .map(
      (prop) =>
        `  ${propertyName(prop.name)}${prop.required ? "" : "?"}: ${typescriptType(prop.rustType)};`,
    )
    .join("\n");
  const events = component.events
    .map((event) => {
      const parameters = event.parameters
        .map((parameter) => `${parameter.name}: ${typescriptType(parameter.rustType)}`)
        .join(", ");
      return `  ${reactEventName(event.name)}?: (${parameters}) => void;`;
    })
    .join("\n");

  return `// Generated by @vooya/vite. Do not edit.
import type { Component } from "solid-js";

interface ${component.name}Props {
${props}
${events}
  onError?: (error: { stage: ${ERROR_STAGE_UNION}; cause: unknown }) => void;
  class?: string;
  className?: string;
}

declare const component: Component<${component.name}Props>;

export default component;
`;
}

function typescriptType(rustType: string) {
  if (/^(?:[iu](?:8|16|32|64|128|size)|f(?:32|64))$/.test(rustType)) return "number";
  if (rustType === "bool") return "boolean";
  if (rustType === "String") return "string";
  throw new Error(`Unsupported Voo contract type "${rustType}".`);
}


function propertyName(name: string) {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function reactEventName(name: string) {
  const pascal = name
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join("");
  return `on${pascal}`;
}
